[toolchain]
# When updating the version, also update Cargo.toml's rust-version
channel = "1.88"
components = ["rustfmt", "clippy", "rust-analyzer", "rust-src"]
targets = ["x86_64-unknown-none", "wasm32-unknown-unknown"]
profile = "minimal"
